### ISSUE TITLE
Add a i18n Entry for the Draft Action

### ISSUE THREAD

**Issue by rysospicy** [vigetlabs/active_versioning_workflow#5]
Add:

```
en:
  active_versioning:
    actions:
      draft: 'Save Draft'
```

Update the `DraftActions` button label:

```
action :submit, label: :draft

# to..

action :submit, label: t('active_versioning.actions.draft')
```
